title: Julian Enggarrio
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://enggarr.io

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  